[build]
  command = "CI=false npm install && CI=false npm run build"
  publish = "build"
  # This command tells Netlify to skip builds unless manually triggered
  ignore = "git diff --quiet HEAD^ HEAD ./public/ ./src/ || exit 1"

# This ensures all deployments go to your specific site
[site]
  id = "154b08a8-604f-4470-abe2-9044f1dc21fe" 