[build]
  command = "./netlify-build.sh"
  publish = "build"

[build.environment]
  DISABLE_TYPESCRIPT = "false"
  SKIP_PREFLIGHT_CHECK = "true"
  NODE_OPTIONS = "--openssl-legacy-provider"
  DISABLE_NEW_JSX_TRANSFORM = "true"
  TSC_COMPILE_ON_ERROR = "true"
  NODE_ENV = "production"
  CI = "false"
  PUBLIC_URL = "/"

# Branch-specific build settings
[context.branch-deploy]
  command = "./netlify-build.sh"

[context.branch-deploy.environment]
  NODE_ENV = "development"

[context.deploy-preview]
  command = "./netlify-build.sh"

[context.deploy-preview.environment]
  NODE_ENV = "development"

# This ensures all deployments go to your specific site
[site]
  id = "154b08a8-604f-4470-abe2-9044f1dc21fe"

# SPA Settings
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.images]
  compress = false

# SPA fallback - this needs to be before the catch-all redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# API redirects for email endpoints
[[redirects]]
  from = "/api/email/contact"
  to = "/.netlify/functions/send-contact-email"
  status = 200

[[redirects]]
  from = "/api/email/order"
  to = "/.netlify/functions/send-order-email"
  status = 200

# Basic headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type" 