[build]
  command = "node pure-build.js"
  publish = "build"

# Completely disable all processing
[build.processing]
  skip_processing = true

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects for email endpoints
[[redirects]]
  from = "/api/email/contact"
  to = "/.netlify/functions/send-contact-email"
  status = 200

[[redirects]]
  from = "/api/email/order"
  to = "/.netlify/functions/send-order-email"
  status = 200

# Basic headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type" 