[build]
  command = "CI=false npm install && CI=false npm run build"
  publish = "build"

# This ensures all deployments go to your specific site
[site]
  # You need to replace this with your actual Netlify site ID
  # Find this in Site settings → General → Site details → Site ID  
  id = "YOUR_ACTUAL_SITE_ID_HERE" 