[build]
  base = "."
  publish = "build"
  command = "node firebase-cors-build.js"

[build.environment]
  REACT_APP_PATH_PREFIX = ""
  DISABLE_TYPESCRIPT = "true"
  SKIP_TYPESCRIPT_CHECK = "true"
  TSC_COMPILE_ON_ERROR = "true"
  SKIP_PREFLIGHT_CHECK = "true"

[build.processing]
  skip_processing = true

[dev]
  publish = "build"
  functions = "netlify/functions"
  port = 8888
  framework = "#static"

# First ensure all API endpoints redirect properly
[[redirects]]
  from = "/api/email/contact"
  to = "/.netlify/functions/send-contact-email"
  status = 200

[[redirects]]
  from = "/api/email/order"
  to = "/.netlify/functions/send-order-email"
  status = 200

# Then handle SPA routing - this must be last!
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/firebasetest"
  to = "/.netlify/functions/test"
  status = 200
