[build]
  base = "."
  publish = "build"
  command = "node install-typescript.js && node purge-typescript.js && node production-build.js"

[build.environment]
  REACT_APP_PATH_PREFIX = ""
  DISABLE_TYPESCRIPT = "true"
  SKIP_TYPESCRIPT_CHECK = "true"
  TSC_COMPILE_ON_ERROR = "true"
  SKIP_PREFLIGHT_CHECK = "true"

[build.processing]
  skip_processing = true

[dev]
  publish = "build"
  functions = "netlify/functions"
  port = 8888
  framework = "#static"

# First ensure all API endpoints redirect properly
[[redirects]]
  from = "/api/email/contact"
  to = "/.netlify/functions/send-contact-email"
  status = 200

[[redirects]]
  from = "/api/email/order"
  to = "/.netlify/functions/send-order-email"
  status = 200

# Direct paths to Netlify functions - ensures compatibility with fix
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Then handle SPA routing - this must be last!
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add security headers with extremely permissive CSP
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src * data: blob: filesystem: about: ws: wss: 'unsafe-inline' 'unsafe-eval'; connect-src * data: blob: 'unsafe-inline'; font-src * data: blob: 'unsafe-inline'; frame-src * data: blob:; img-src * data: blob: 'unsafe-inline'; manifest-src * data: blob:; media-src * data: blob:; object-src * data: blob:; script-src * data: blob: 'unsafe-inline' 'unsafe-eval'; style-src * data: blob: 'unsafe-inline'; worker-src * data: blob:;"
    Access-Control-Allow-Origin = "*"
