name: Deploy to Firebase Staging

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Build & Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci
        
      - name: Build Project
        run: npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          SKIP_PREFLIGHT_CHECK: true

      - name: Deploy to Firebase Staging
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: buttonsflowerfarm-8a54d
          channelId: live
          target: staging 